export const LOADING = 'LOADING';
export const SUCCESSFUL_SIGN_UP = 'SUCCESSFUL_SIGN_UP';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export const SUCCESSFUL_LOGIN = 'SUCCESSFUL_LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SIGN_OUT = 'SIGN_OUT';

export const UPLOAD_FILE = 'UPLOAD_FILE';
export const SUCCESSFUL_FILE_UPLOAD = 'SUCCESSFUL_FILE_UPLOAD';
export const FAILED_FILE_UPLOAD = 'FAILED_FILE_UPLOAD';
export const LINK_CREATED_SUCCESSFULLY = 'LINK_CREATED_SUCCESSFULLY';
export const ERROR_CREATING_LINK = 'ERROR_CREATING_LINK';
export const ADD_DOWNLOADS = 'ADD_DOWNLOADS';
export const ADD_PASSWORD = 'ADD_PASSWORD';
export const CLEAN_STATE = 'CLEAN_STATE';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';